### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by casualgc** [Masstronaut/slot_array#1]
I see a couple of lines like this,

https://github.com/Masstronaut/slot_array/blob/00c21a019c6cd8cb9bf9a32b151029f42889b1a7/slot_map.hpp#L214

shouldn't they really be
   const auto &generation{ std::get<1>( key ) };
?

**Comment by Masstronaut** [comment]
@casualgc you are correct, those were incorrectly written once and then copy+pasted several more times.

Not only have I resolved this, but I also added some private functions for accessing and mutating the key parts that are much clearer in their intention than std::get<>.

Thank you for the feedback!
